name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure this matches the Node version you're using

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: List files
        run: ls -alh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
